on:
  issues:
    types:
      - opened

jobs:

  add-jira-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh issue --repo ${{github.repository}} edit ${{github.event.issue.number}} --add-label "jira"
        env:
          GH_TOKEN: ${{ github.token }}
